### ISSUE TITLE
Issue with first hour chemical outputs

### ISSUE THREAD

**Issue by zmoon** [NOAA-EMC/AQM#67]
## Description:

In our recent runs, we noticed that in our outputs, the concentrations drop to low (species- and time-dependent) values in the first hour, but otherwise look normal. Someone in our group suggested that it could be that the data is getting written out before the initial condition from the previous cycle is read.

This occurs for chemical species in the `dyn.f???` and `aqm.prod` files.

<details>
<summary>
Some details for variables <code>pm25_ave</code>,  <code>o3_ave</code>, <code>no2_ave</code>
</summary>

From `dyn.f???` files :point_down:

![pg1 timeseries OZONE 2019-08-01_12 2019-08-11_11 all CONUS](https://user-images.githubusercontent.com/15079414/223223109-77cb3073-aebd-4b99-bea6-2abfe0822c8c.png)

Demonstrating the species and time dependence of the low 12z values (domain-mean time series at 12z) :point_down:
```
                     pm25_ave    o3_ave   no2_ave
time
2019-07-21 12:00:00  0.153723  1.322011  0.019540
2019-07-22 12:00:00  0.146690  1.309766  0.021433
2019-07-23 12:00:00  0.140355  1.300713  0.021501
2019-07-24 12:00:00  0.142170  1.310394  0.022272
2019-07-25 12:00:00  0.153580  1.337568  0.022722
2019-07-26 12:00:00  0.146568  1.347833  0.023340
2019-07-27 12:00:00  0.149825  1.341450  0.020660
2019-07-28 12:00:00  0.153799  1.333693  0.019473
2019-07-29 12:00:00  0.152903  1.332540  0.021367
2019-07-30 12:00:00  0.152387  1.329104  0.022803
2019-07-31 12:00:00  0.151989  1.326439  0.022962
2019-08-01 12:00:00  0.154016  1.332624  0.023092
2019-08-02 12:00:00  0.156643  1.341431  0.023334
2019-08-03 12:00:00  0.156332  1.350270  0.021242
2019-08-04 12:00:00  0.159756  1.344413  0.020541
2019-08-05 12:00:00  0.159777  1.341120  0.023360
2019-08-06 12:00:00  0.160934  1.344035  0.022252
2019-08-07 12:00:00  0.159502  1.348051  0.022330
2019-08-08 12:00:00  0.157596  1.343187  0.021879
2019-08-09 12:00:00  0.154045  1.342660  0.022002
2019-08-10 12:00:00  0.150674  1.342777  0.021307
```

From `aqm.prod` files 👇 

![pg1b timeseries OZONE 2019-08-01_12 2019-08-11_11 all CONUS](https://user-images.githubusercontent.com/15079414/223223163-5c8330ab-bf89-4402-8d5e-9d94460146ba.png)

</details>

**Comment by zmoon** [comment]
@drnimbusrain could you add some info about the config etc.?

**Comment by drnimbusrain** [comment]
These are "community" runs we are doing on Hera, and the example for Zach's plots above is for a continuous/warm start run on Aug 01-10, 2019.  Here is the configuration for these runs:  

```
/scratch2/NAGAPE/arl/Patrick.C.Campbell/run_ufs-srw-app_online-cmaq/run_na_test_ufs-srw-app-arl-base_20230215/ush/config.yaml
```
```
metadata:
  description: config for Online-CMAQ, AQM_NA_13km, Community mode, 1cycle a day
user:
  RUN_ENVIR: community
  MACHINE: hera
  ACCOUNT: naqfc
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 3
  EXPT_BASEDIR: /scratch1/NCEPDEV/stmp4/Patrick.C.Campbell/expt_dirs
  EXPT_SUBDIR: aqm_cold_aqmna13_Aug01-Aug10_gfsv16_arl-base_no-canopy_fengsha_pt
  PREDEF_GRID_NAME: AQM_NA_13km
  CCPP_PHYS_SUITE: FV3_GFS_v16
  DATE_FIRST_CYCL: '2019080112'
  DATE_LAST_CYCL: '2019081012'
  FCST_LEN_HRS: 24
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
  DIAG_TABLE_TMPL_FN: diag_table_aqm.FV3_GFS_v16
  FIELD_TABLE_TMPL_FN: field_table_aqm.FV3_GFS_v16
nco:
  NET: aqm
workflow_switches:
  RUN_TASK_MAKE_GRID: true
  RUN_TASK_MAKE_OROG: true
  RUN_TASK_MAKE_SFC_CLIMO: true
  RUN_TASK_RUN_POST: false
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
task_run_fcst:
  DT_ATMOS: 180
  LAYOUT_X: 50
  LAYOUT_Y: 34
  BLOCKSIZE: 16
  RESTART_INTERVAL: 1 -1
  WTIME_RUN_FCST: 02:00:00
  QUILTING: true
  PRINT_ESMF: false
task_run_post:
  POST_OUTPUT_DOMAIN_NAME: 793
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
  HALO_BLEND: 0
cpl_aqm_parm:
  CPL_AQM: true
  RUN_TASK_AQM_ICS: true
  RUN_TASK_AQM_LBCS: true
  RUN_TASK_NEXUS_GFS_SFC: true
  RUN_TASK_NEXUS_EMISSION: true
  RUN_TASK_FIRE_EMISSION: true
  RUN_TASK_POINT_SOURCE: true
  DO_AQM_CHEM_LBCS: true
  DO_AQM_GEFS_LBCS: true
  AQM_CONFIG_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/aqm/epa/data
  AQM_BIO_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/aqm/bio
  AQM_BIO_FILE: BEIS_RRFScmaq_C775.ncf
  DO_AQM_DUST: true
  AQM_DUST_DIR: /scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus/FENGSHA/Online_CMAQ
  AQM_DUST_FILE_PREFIX: FENGSHA_p8_10km_inputs
  AQM_DUST_FILE_SUFFIX: .nc
  DO_AQM_CANOPY: false
  AQM_CANOPY_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/canopy
  AQM_CANOPY_FILE_PREFIX: gfs.t12z.geo
  AQM_CANOPY_FILE_SUFFIX: .canopy_regrid.nc
  AQM_FIRE_DIR: /scratch2/NCEPDEV/naqfc/Jianping.Huang/Data/emissions/GSCE/RAVE.in.793/RAVE_RT
  AQM_FIRE_FILE_PREFIX: Hourly_Emissions_regrid_NA_13km
  AQM_FIRE_FILE_SUFFIX: _h72.nc
  AQM_RC_FIRE_FREQUENCY: hourly
  DO_AQM_PRODUCT: true
  AQM_LBCS_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ_NA13km/LBCS/RRFS_NA13km_AM4_v1/
  AQM_LBCS_FILES: am4_bndy.c793.2019<MM>.v1.nc
  AQM_GEFS_DIR: /scratch1/NCEPDEV/rstprod/nexus_emissions/RRFS-BOUNDARY/GEFS_Aerosol
  AQM_GEFS_FILE_PREFIX: gfs
  AQM_GEFS_FILE_CYC: 00
  NEXUS_INPUT_DIR: /scratch1/RDARCH/rda-arl-gpu/Barry.Baker/emissions/nexus
  NEXUS_FIX_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/nexus/fix
  NEXUS_GRID_FN: grid_spec_793.nc
  NUM_SPLIT_NEXUS: 3
  COLDSTART: false
  WARMSTART_CYCLE_DIR: /scratch1/NCEPDEV/stmp4/Patrick.C.Campbell/expt_dirs/aqm_cold_aqmna13_Jul21-Jul31_gfsv16_arl-base_no-canopy_fengsha_pt/2019073112
```
